export const stateNames = [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Goa*', 
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala***',
    'Ladakh',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Uttarakhand',
    'Manipur',
    'West Bengal',
    'Odisha',
    'Rajasthan',
    'Sikkim',
    'Meghalaya',
    'Punjab**',
    'Mizoram',
    'Telangana',
    'Tripura',
    'Puducherry',
    'Uttar Pradesh',
    'Nagaland',
    'Tamil Nadu',
]